### ISSUE TITLE
Randomness attack vectors

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#103]
Currently, when a transcoder calls `claimWork`, the current block hash is used to determine which segments are challenged for verification such that:

`segNo` is challenged for verification if `h(blockNumber, blockHash, segNo) % verificationRate` == 0.

The idea here is that a transcoder will not know what the block hash is when it calls `claimWork` so it will not be able to determine which segments are challenged for verification until it actually calls `claimWork`. However, this property does not hold in the case of a transcoder also being an Ethereum miner because the miner can control the block hash at the time of a call to `claimWork`.

A miner/transcoder could send garbage data to the broadcaster as a part of its transcoded stream, while holding onto all of the broadcasted segment data. When the miner/transcoder calls `claimWork`, it can generate blocks until it finds a block hash that guarantees that certain segments are challenged which can be known ahead of time. The miner also has a bit of flexibility because it can choose when to call `claimWork` and only call it when it has mined a block with a favorable block hash. If the miner knows which segments are challenged, it can selectively transcode the segments that will be challenged. The rest of the transcode receipts will contain the hash of garbage data for the `transcodedDataHash` field. As a result, the transcoder will be able to pass verification for the challenged segments since they were transcoded properly, and will be able to get away with submitting garbage data for non-challenged segments.

The cost of the attack is the lost block reward - the miner runs the chance of losing block reward if it keeps generating new blocks in search of a favorable block hash and an honest miner submits its mined block before the dishonest miner. This attack is only worth it for the miner/transcoder if the value of the LPT fees that can be distributed from a `claimWork` call is > `block reward * # of tries to get a favorable block hash`. This would likely only potentially be the case for very long lived streams with many segments.

This can be mitigated by broadcaster challenges. A transcoder sends signed transcoded segments to the broadcaster off-chain so a broadcaster can observe that the transcoded data it received is different from the transcoded data submitted as a part of a transcode receipt when a transcoder calls `verify` for a challenged segment. Since the transcoded segment is signed, the broadcaster can prove to the contract that the transcoder sent it garbage data, but submitted valid transcoded data for verification. A successful proof could slash the transcoder.

A transcoder can send garbage data to the broadcaster, but it cannot selectively send the broadcaster valid transcoded segments for challenged segments and garbage data for un-challenged segments, because it would've already sent the segments off-chain by the time it can determine the challenged segments when it calls `claimWork`.

**Comment by dob** [comment]
One other solution is that instead of using the **current** blockhash to determine which segments are challenged, we could use the **next** blockhash. This way the commitment has to be made prior to being able to affect the block hash to be used, so rather than deciding whether to commit + submit a block due to the conditions aligning correctly, you would be taking on slashing risk proportional to the % of garbage segments you committed to.

**Comment by yondonfu** [comment]
Good point, so as a miner/transcoder you would only be able to influence the next block hash after already committing in the previous block if you win the race to mine the next block. Your probability of mining the next block would also decrease with the number of attempts at generating a favorable block hash.

**Comment by dob** [comment]
The latest update here uses `block.blockhash(block.number - 1)` which is definitely not random and would allow the transcoder to craft his claim to know which segments would be challenged. We had to change it to this because we couldn't get block number beyond 250 blocks.

One solution to this would be to limit the verification period to less than 250 blocks (62 minutes). Another would be to use a random oracle, that can put some reliable random number on chain for every block number, (such as the block hash), which would give us the source of randonmess that can always be looked up regardless of how many blocks have passed.

**Comment by ericxtang** [comment]
Yikes... What's the downside of limiting the verification period to less than 256 blocks for now?  It feels like the oracle change is a potential big change.

**Comment by yondonfu** [comment]
The main downside of limiting the verification period to less than 256 blocks is a potentially constantly decreasing verification period if block times decrease. However, at the same time, based on some offline discussions, that might be something that is fixed in a follow-up protocol update in the interest of immediately fixing other vulnerabilities and making other more crucial improvements right now.

In the interest of continuing the discussion in search of a better solution though, below is a scheme I got started thinking about. A big downside is that broadcasters have to submit 2 transactions for every job, but perhaps this can be reduced in future iterations...

Broadcaster calls `job(streamId, transcodingOptions, endBlock, h(R))` s.t. `R` is some random number and `h(R)` is the hashed commitment of `R`.  The transcoder submits claims on-chain up until `endBlock`. After the `endBlock` is `challengePeriod` blocks, during which the broadcaster can call `challengeClaims(jobId, R)` to reveal `R` which must match the original hashed commitment `h(R)`. If the broadcaster does not call `challengeClaims(jobId, R)` within `challengePeriod` blocks, no segments are challenged for the transcoder's claims. `R` is used as the random seed to determine which segments to challenge based on the current `verificationRate`. After the challenge period, the transcoder has `verificationPeriod` blocks to submit challenged segments for verification. After the verification period is the slashing period during which watchers can slash the transcoder for failing to submit a challenged segment for verification. The broadcaster can withdraw after the end block for a job because at this point fees will be in escrow already. 

A possible improvement with only a single transaction by the broadcaster involves the broadcaster sending `E(R)` (`R` encrypted using the transcoder's public key)  to the transcoder off-chain during the challenge period. The transcoder decrypts `E(R)` to get `R` and can check if `R` matches the on-chain hashed commitment. The transcoder then includes `R` when submitting a segment for verification; the smart contract checks that `R` matches the previous hashed commitment and uses it as the random seed for checking if a segment should be verified. The big problem here is that if a broadcaster withholds `R` during the challenge period, a transcoder can't prove that the broadcaster did not send `R`.

**Comment by dob** [comment]
I think with the merging of #114 we should leave this issue open for the future, but remove the pre-audit milesone. I'll do that now.

**Comment by yondonfu** [comment]
Closing this issue because the protocol no longer involves block hash based random sampling of segment commitments in Streamflow.
