### ISSUE TITLE
Calling BondingManager.transcoder() does not update transcoderStatus

### ISSUE THREAD

**Issue by jozanza** [livepeer/protocol#105]
Using the BondingManager on the [develop branch](https://github.com/livepeer/protocol/tree/develop), I'm able to successfully call the [`transcoder()`](https://github.com/livepeer/protocol/blob/develop/contracts/bonding/BondingManager.sol#L109). However, my transcoder status remains `NotRegistered` unless I have previously called [`bond()`](https://github.com/livepeer/protocol/blob/develop/contracts/bonding/BondingManager.sol#L162).

In most cases, I'm sure users would want to bond to themselves as a transcoder candidate, however, it might also be nice to allow users to becomes candidates without any stake.

**Comment by yondonfu** [comment]
If you were using the BondingManager by pulling the address from the Controller registry I suspect that it is related to this issue https://github.com/livepeer/protocol/issues/112 which will be looked into

**Comment by jozanza** [comment]
Yeah that's exactly what I was doing. I'll keep my eye on #112 💯

**Comment by yondonfu** [comment]
Sounds good, this issue shouldn't be a problem right now since the proxy contracts are currently removed from migrations on the master branch until a fix for that issue comes, so I'm closing this issue and we can track progress in the ManagerProxy issue
