### ISSUE TITLE
Investigate ManagerProxy contract intermittent transaction failures 

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#112]
The ManagerProxy contract is currently removed from the migrations because we were seeing some seemingly non-deterministic behavior when running an integration test to register transcoders and have delegators bond to those transcoders. Transactions via the proxy contract would fail sometimes and succeed other times. The same types of interactions are tested for in the unit test for BondingManager so it does not appear to be an issue with the BondingManager, but instead might be an issue with our currently implementation of the ManagerProxy and how data is being handled in the proxy contract fallback function. After investigating and finding a fix we can add the ManagerProxy contract back into the migrations

**Comment by dob** [comment]
Just checking in that 

A) This is still open?
B) This means that we can not use our contract upgrade mechanism until we reintroduce, correct?

**Comment by yondonfu** [comment]
The proxies have been added back into the migration scripts and a simple integration test that interacts with the proxies is passing with TestRPC, but this has not been tested with other clients yet (since integration tests use a custom RPC method that only TestRPC defines). We can probably close this as I don't think there is anything contract specific todos
