### ISSUE TITLE
Adding a transcoder to the reserve pool when it is full

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#117]
If the reserve pool is full and a transcoder tries to join the reserve pool (it does not have enough stake to join the candidate pool), it will be rejected even though the transcoder might have more stake than one of the transcoders in the reserve pool. This is because the reserve pool is implemented as a max-heap and we only ever know the reserve transcoder with the most stake in the reserve pool, but we can't determine whether the transcoder trying to join the reserve pool has more stake than some other transcoder in the reserve pool.

This could be solved if the reserve pool was a min-heap, but we would lose the ability to efficiently promote a reserve transcoder to a candidate transcoder if an existing candidate transcoder loses stake such that its updated stake is less than the reserve transcoder with the greatest stake.

**Comment by dob** [comment]
I think we're using the wrong data structure. How about a sorted, fixed size array of length `n`?

When a candidate transcoder gets more bonded stake, we could:

1. Check if the their stake is greater than `arr[n-1]`. If not, we're done.
2. Check if their stake is greater than `arr[0]`. If so, promote into the active set, and use the evicted node as the new candidate to insert into reserve set.
3. If it belongs in the reserve set, or if we have a new candidate, binary search the array for insertion position.
4. Insert the candidate into proper position, and evict the last element.

What do we think? O(log n) iterations if we can construct the new candidate set storage array efficiently.

Another option on the simple side is if the candidate set is of a reasonable fixed size (say 20?) then we don't even worry about ordering, just keep a pointer to min + max, and loop to update min or max when necessary.

**Comment by yondonfu** [comment]
Are you saying that the reserve set is a sorted, fixed size array and the candidate set is still a min-heap? Also when you say candidate transcoder are you referring to the transcoder that is attempting to join one of the sets?

Also, I think that scheme is actually O(n) since you have to shift all the elements in the array after inserting and before evicting the last element

**Comment by dob** [comment]
> Just to clarify - are you saying that the reserve set is a sorted, fixed size array and the candidate set is still a min-heap?

Yes.

> Also when you say candidate transcoder are you referring to the transcoder that is attempting to join one of the sets?

Yes, either the new transcoder trying to join the "reserve" set, or the transcoder evicted from the "candidate" set if the new transcoder had enough to join the active pool. 

And related to O(n) to resize an array, yah that makes sense, I wasn't sure of underlying implementation for insert operations. A linked list with max/min pointers would be ok but let's no go crazy. 

The more I think about it the more I think it might be reasonable for now just to have a fixed size candidate array with min/max pointers (not sorted). If you're bonding towards someone to the point that pushes them into the reserve pool, or up to the candidate pool, then you pay the cost of looping over the reserve pool to update the min/max pointers. The fixed size could just be something reasonable like 30-50, if we can handle that much in a loop.

What do you think? We may have overoptimized for huge active transcoder sets when doing the heap implementation, whereas that may not be a problem faced for awhile.

**Comment by yondonfu** [comment]
Yeah I think it'll be reasonable to use an array with min/max pointers for the reserve set and a min-heap for the candidate set. The insertion into the reserve set array will be O(n) reads, but we should still have O(1) writes which should give us a little bit of wiggle room in terms of how big the array can be

**Comment by yondonfu** [comment]
Closed by #119
