### ISSUE TITLE
Protocol parameters representing percents need more granular representation

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#124]
Right now we use `uint` to represent protocol parameters denominated in percents such as slash percentages and inflation rates. We need something more granular since we may want values < 1% or even intermediate values like 24.334%.

I'd suggest using a CONSTANT represented denominator of 10^6 (1,000,000), and storing the parameters as the numerator. So for example, a slash rate of 1.3% would be stored as the uint 13000.

Anywhere the contracts currently multiply by the param and divide by 100, we would instead multiply by the param and divide by the CONSTANT DIVISOR.

**Comment by yondonfu** [comment]
Closed by #125
