### ISSUE TITLE
Consider what happens when we hit the max value of uint256 while minting

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#143]
We should consider what the behavior should be if the max value of uint256 is ever reached while increasing the total supply of the token by minting. If we ever reach this scenario something would have gone wrong i.e. no one is participating in the protocol, but it might be helpful to have safeguards to ensure liveness (as opposed to overflowing) in round progression. One option might be to just return rather than revert if any additional minting would cause an overflow

**Comment by dob** [comment]
Yah, also lets keep in mind limits imposed not just by hitting the max
token value, but also by any multiples that we use when calculating
percentages and whatnot. So we may actually have liveness issues if we come
with a multiple of 10^6 of the max, so better to cap it at that number or
even something lower for safety.
