### ISSUE TITLE
New 

### ISSUE THREAD

**Issue by rayj00** [livepeer/protocol#149]
**So..a new characteristic of Livepeer Broadcasting: I start up Livepeer -testnet -v 4. It sits at:** 
I0119 10:07:56.790594 10170 lpms.go:56] HTTP Server listening on :8935
I0119 10:07:56.790628 10170 lpms.go:52] LPMS Server listening on :1935

**I then start a stream and it sits at:**

I0119 10:09:25.279295 10170 listener.go:32] RTMP server got upstream: rtmp://23.239.31.177:1935/movie
I0119 10:09:26.147195 10170 mediaserver.go:138] Current deposit is: 1
I0119 10:09:26.147491 10170 mediaserver.go:266]

ManifestID: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a9866c798cf314d0ef3717cc24c31b74b8219ac42bf54b8fc6efbf545a6b98d8eb3

I0119 10:09:26.147588 10170 mediaserver.go:267]

hlsStrmID: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a9866c798cf314d0ef3717cc24c31b74b8219ac42bf54b8fc6efbf545a6b98d8eb3P720p30fps16x9

I0119 10:09:26.147668 10170 lpms.go:96] Segment RTMP Req: rtmp://localhost:1935/stream/12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a9811ef2f37dad14f7310093e9c016faa9a5f60d3a5162b941c17976c573c7d5db8RTMP
I0119 10:09:26.148760 10170 video_segmenter.go:93] Ffmpeg path:
I0119 10:09:26.204948 10170 player.go:55] LPMS got RTMP request @ rtmp://localhost:1935/stream/12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a9811ef2f37dad14f7310093e9c016faa9a5f60d3a5162b941c17976c573c7d5db8RTMP
I0119 10:09:36.555629 10170 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0119 10:09:36.677772 10170 basic_network.go:480] Received a message 2 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0119 10:09:36.677821 10170 basic_network.go:562] Handling sub req for 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a9866c798cf314d0ef3717cc24c31b74b8219ac42bf54b8fc6efbf545a6b98d8eb3P720p30fps16x9
I0119 10:09:36.677945 10170 basic_notifiee.go:57] Notifiee - OpenedStream: 12208f3498ad1516608fa42214ef6cc16b0d76cd935cdb80ee765e710eb7fa248a98 - 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0119 10:09:36.678117 10170 basic_network.go:480] Received a message 4 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01
I0119 10:09:37.315593 10170 livepeernode.go:133] Created broadcast job. Price: 1. Type: 93c717e7c0a6517a

**This is different as I am not seeing segments (.ts) files being created.**

**As soon as start up the player, I see one message in the log:** 

I0119 10:13:44.937863 10170 basic_network.go:480] Received a message 5 from 12208a4eb428aa57a74ef0593612adb88077c75c71ad07c3c26e4e7a8d4860083b01

**And the player is saying: This broadcaster is currently offline
I am never seeing segments or any video!**

**My Eth account adr is: 0x2256862563D922483c3d698e17E239344B487c86**

**Comment by yondonfu** [comment]
This is more of a [go-livepeer](https://github.com/livepeer/go-livepeer) issue - this repo is primarily focused on the Ethereum contracts for the Livepeer protocol so closing this for now.
