### ISSUE TITLE
Remove nodegit as a dependency

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#152]
We use the nodegit package's Node.js bindings to retrieve the head Git commit hash when registering a contract with the Controller. This package has caused some installation headaches, so it might be a good idea to remove the dependency and instead write a small script to retrieve the Git commit hash

**Comment by j0sh** [comment]
`git rev-parse HEAD` should do the trick.

**Comment by jozanza** [comment]
Just opened a PR for this update: https://github.com/livepeer/protocol/pull/153

**Comment by yondonfu** [comment]
Closed by #153
