### ISSUE TITLE
Ensure that all protocol parameters that should be updated have setters

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#159]
All protocol parameters that are expected to be updated in the future should have associated setters. For example, `roundLockAmount` in `RoundsManager` is a protocol parameter, but currently does not have a setter.

Additionally, if we have setters for individual parameters, I don't think we need a batch setter like `setParameters`. The plus of the function is that when we are deploying the contracts or when doing batch updates to protocol parameters, we can call a single function to set all of them. The con is that it just adds more code to the contracts that is not strictly necessary and adds potential confusion around usage and I’m not sure if the slight benefit in being able to set the values of multiple parameters is that significant when the individual setters can always be invoked on their own especially if the batch update case is primarily during deployment (and in that case we could always wrap the calls to the individual setter functions in a contract if we really needed the transaction to be atomic)

**Comment by ericxtang** [comment]
We should also add `require(MathUtils.validPerc())` for roundLockAmount`
