### ISSUE TITLE
Block-time proof the inflation in the protocol

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#16]
If the block times change it could affect our inflation rate. We need a solution that maintains our yearly inflation target regardless of underlying block times.

**Comment by yondonfu** [comment]
Maybe we should just set the inflation rate as a per round value and eliminate the yearly inflation rate (which we just use to compute the per round inflationary rewards anyway). Then, we can remove the function that computes the per round inflationary rewards which currently relies on a hard coded block time to determine how many rounds are in a year. We still set the round length value keeping in mind how often inflationary rewards should be distributed and if block times change such that the rounds become too short, the round length can be extended via governance

**Comment by dob** [comment]
Yes, I like this idea. The yearly rate can just be calculated at the UX
level to give people a consumable number, but within the protocol it can
move per-round.
