### ISSUE TITLE
Slashing fixes

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#162]
Tracking a few slashing related fixes in this issue:

- `slashTranscoder` in `BondingManager` currently always fails for an active transcoder because `activeTranscoderTotalStake` will always fail if the transcoder being slashed is set as inactive first. The order of operations in `slashTranscoder` should be changed such that the total active stake for the round is decremented by the value returned by `activeTranscoderTotalStake` BEFORE setting the transcoder as inactive.
- `slashTranscoder` should not check that a transcoder is registered. Currently, the check causes 2 problems:
    - A transcoder that unbonds and automatically resigns as a transcoder becomes unslashable
    - A transcoder that is slashed can still call `claimWork` and fault, but it becomes unslashable
    the second time since it is no longer registered

**Comment by ericxtang** [comment]
With this fix, which amount will we be slashing?  Unbonded transcoders will already have taken out their bondedAmount, and can potentially withdraw their delegatedAmount after the unbonding period.

**Comment by yondonfu** [comment]
`bondedAmount` - If a transcoder calls `unbond`, this amount can still be slashed and decreased during the unbonding period.

Although that made me realize that removing the check for a registered transcoder in `slashTranscoder` might not be enough - if a transcoder can still call `claimWork` even after it has unbonded and resigned (since `claimWork` does not check if a transcoder is registered) the transcoder can wait until the very end of the unbonding period, quickly call `claimWork` to drain the broadcaster and then withdraw its stake to avoid being slashed for a fault. This could be fixed by marking the job as inactive if any transcode claim for that job triggered a slash and prevent submitting transcode claims for inactive jobs.
