### ISSUE TITLE
Delegators that unbond and then bond before the unbonding period is over become stuck

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#166]
@ericxtang found this bug where a delegator can end up in a weird state such that it cannot perform any bonding related actions including withdrawing its stake:

Delegator A is bonded to transcoder B.  A calls `unbond()` - as a result A now has a `withdrawRound`, a null `delegateAddress` and is in the unbonding state. Additionally, in the process of calling `unbond()`, A's last claim round is set to the current round N. 1 round passes. Before the unbonding period is over, A calls `bond()` towards B. Now, A has a `withdrawRound`, a `delegateAddress` set to the address of B and a `startRound` set to 0 (`bond()` only sets your `startRound` if you are in the unbonded state OR you are already delegated towards someone and are delegating to someone else - in this case A is in the unbonding state and is not already delegated to someone). Note that 1) the claimable stake for B's token pools in round N + 1 does not include A's bonded stake because it was locked in for that round before A bonded toward B 
 2) A's last claim round is still set to N, but the current round is N + 1. Let's say 5 rounds pass and now the current round is N + 6 and B's token pools for each round was initialized with its claimable stake. Now, if A tries to call any bonding related function thereby automatically claiming rewards and fees from past rounds, it will try to claim rewards and fees starting from round N. As a part of claiming rewards and fees for a round, A's bonded stake is subtracted from B's claimable stake for that round. In this case, A's bonded stake > B's claimable stake which causes the transaction to fail.

Fixing this requires two things:
- Ensuring that a delegator cannot call `bond()` if it is in the unbonding state - if a delegator calls `unbond()` it must wait through the unbonding period before it can call `bond()` again if it changes its mind and decides that it does not want to withdraw its stake and instead wants to bond to someone again
- If a delegator claims rewards and fees through a certain round by calling `unbond()`, if it decides to `bond()` again after the unbonding period, it should now claim rewards and fees starting from the last claim round because from its last claim round through the current round it was not bonded to anyone. My initial instinct is to just zero out the last claim round if you call `unbond()` and treat the next time you call `bond()` as if you were calling `bond()` for the first time (instead of iterating from 0 through current round, you just skip the claiming process and just set the last claim round to the current round because you were not bonded to anyone from round 0 through current round)

**Comment by ericxtang** [comment]
> Ensuring that a delegator can only call bond() if it is in the unbonding state
It should be "unbonded" state right?
