### ISSUE TITLE
Should delegators be able to unbond and rebond to cancel the delegation period?

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#167]
I don't think the protocol currently supports it.  @dob pointed out that "If we have a multi week or month unbonding period, it would be kind of lame if you couldn’t cancel it to rebond towards someone else. Especially since we don’t have partial unbonding."

**Comment by yondonfu** [comment]
This feels like a feature that might be neat in the future, but that is not crucial right now because I think the additional complexity outweighs the slightly better UX. Plus you always bond with a different account if you have one account that is currently sitting through the unbonding period

**Comment by dob** [comment]
I think it's ok to punt this to the future, but I'd disagree about "always being able to bond from a different account." If all my stake is tied up for weeks or months on one account which is being unbonded, I have no economic power to participate in the protocol during that time.

So yes, ok to wait to address, but I suspect this will cause a lot of dis-engagement when people are eager to engage.

**Comment by yondonfu** [comment]
Hm I was referring to the *possibility* of a users spreading their tokens across multiple accounts such that they can participate with another account even if another account is in the unbonding period. However, I guess this is something that would only be more common among more sophisticated stakeholders and adds additional friction as you mention...

So I don't think the implementation actually requires too much additional complexity - I'll see if any additional concerns comes up...
