### ISSUE TITLE
More descriptive naming for functions

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#168]
Using this issue to track naming related improvements and fixes

- [x] `slashingPeriod` -> `verificationSlashingPeriod`: This value is only relevant for the missed verification slashing condition, but not for general slashing conditions
- [x]  Label functions that trust their caller (i.e. the caller must be a certain address) with `trusted`. Ex. `transferTokens()` -> `trustedTransferTokens()` in `Minter` because it always trusts its caller, `BondingManger`
- [x] `claimTokenPoolsShares` -> `claimEarningsThroughRound`: I think this is clearer than "token pools shares" and earnings captures both rewards and fees
- [x] `autoClaimTokenPoolsShares` -> `autoClaimEarnings`: Same reason as above
- [x] `lastClaimTokenPoolsSharesRound` -> `lastClaimEarningsRound`: Same reason as above
- [ ] `ManagerProxy` -> `DelegateProxy`: More descriptive name. The contract is a proxy that delegates to another contract to execute business logic with its own storage context
- [ ] `ManagerProxyTarget` -> `DelegateProxyTarget`: The target that a proxy contract delegates to.
- [x] `blockRewardCut` -> `rewardCut`: Using the word block when there is no notion of blocks in the protocol is confusing

**Comment by yondonfu** [comment]
@dob @ericxtang Thoughts on the terminology around rewards (i.e. "block reward" vs "reward" or "round reward")? We've been using block reward for awhile. My instinct is that calling it block reward feels weird given the lack of connection between rewards and blocks. The terminology seems to mainly be useful for providing new people an easy/clear point of comparison (BTC and ETH block rewards).

**Comment by dob** [comment]
I think the protocol can use the term "reward", and when providing more color through our writing and speaking we can probably use the term "round reward". "participation reward" is probably a little more accurate, but I don't love it.

**Comment by ericxtang** [comment]
token reward?

**Comment by yondonfu** [comment]
Ended up using "reward" in the protocol for simplicity's sake and I think we can refine how we refer to it extra-protocol whether it be just reward, "round reward" or "token reward".

Also, went with additional descriptive comments for ManagerProxy and ManagerProxyTarget instead of a naming change
