### ISSUE TITLE
Upgrading the Minter

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#171]
Here’s another possibility: keep the Minter as a regular contract that is not upgradeable using the delegate proxy upgrade pattern and replace transferTokenOwnership() with migrateToNewMinter() - this function is only callable by the Controller owner and transfers ownership of the token as well as the current Minter’s token balance to a new Minter. The function can do some additional sanity checks to make sure the new Minter’s controller is the same as the current Minter’s controller (and thus the same owner). The upgrade path for the Minter then becomes: 1) Deploy new Minter 2) Call migrateToNewMinter() on the current Minter 3) Register new Minter with the Controller

**Comment by dob** [comment]
Just noting that the minter also holds ETH, so we'd need to transfer that as well. Just so we don't forget :)
