### ISSUE TITLE
Client generated hints for inserting/updating transcoder order in the pool

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#174]
At the moment, updating a transcoder’s position in the pool requires looping through the entire pool in the worst case, but the situation is not as bad as initializeRound() because it primarily performs storage reads which are significantly cheaper than storage writes and only performs a few constant number of storage writes to actually update the transcoder’s position. So gas limits are still a concern, but not AS much as the concerns for initializeRound(). We do have one potentially helpful alternative here: use the optional hint feature of SortedDoublyLL when updating a transcoder’s position in the pool. The function signature for bond() and unbond() would also accept prevTranscoder and nextTranscoder parameters that represent the new insertion position of the transcoder that the delegator is bonded to. The UI/frontend could perform the hint calculation off-chain and create the appropriate hint to be used for a transaction. This might make auditing/reading the contracts a little more difficult so there is a tradeoff, but just listing it as an alternative option to mitigate gas costs instead of allowing for the reduction of the transcoder pool size which can be complex and expensive.

**Comment by dob** [comment]
I think we save this for a subsequent protocol iteration. I'd rather not change the interfaces to these important functions, and all the tools that interact with them at this stage so close to code freeze. If we have to do a significant pass post-audit then we could consider putting this in.

**Comment by yondonfu** [comment]
Closing because this was implemented for Streamflow.
