### ISSUE TITLE
A transcoder can be slashed, come back and register and then claim work for that job again

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#175]
Currently, if a job has an end block far in the future, a transcoder can be slashed, come back and register and then claim work for that job again. This might not be a big deal though because if the transcoder faults again it will be slashed. 

Should we just set a job as inactive if a transcoder is slashed? Is there ever a scenario where the transcoder could come back and start doing honest work for the job again? I feel like setting the job as inactive would simplifiy logic while reducing flexibity, but I’m not sure the flexibility is needed. However, in a future where multiple transcoders might be able to handle a job perhaps we should just leave the job active
If a transcoder is slashed for a claim and comes back and submits a claim that shares segments with the slashed claim except it is honestly transcoding this time should it be able to be slashed?

**Comment by ericxtang** [comment]
I think if the transcoder comes back and behaves honestly, it should definitely not be slashed.  If it faults again, then it should be slashed again.  Feels like setting the job inactive is a little unnecessary - unless leaving it active exposes a vulnerability.

**Comment by yondonfu** [comment]
> I think if the transcoder comes back and behaves honestly, it should definitely not be slashed.

Agree - slashing will be restricted to claims that have not already been labeled as "slashed"

> Feels like setting the job inactive is a little unnecessary - unless leaving it active exposes a vulnerability

The vulnerability is: lets say a broadcaster creates a job A with the end block set to 200 blocks in the future. The elected transcoder subscribes to the stream, receives signed segments, but then faults by missing verification for challenged segments from a transcode claim and is slashed by a watcher. No one is transcoding the broadcaster's stream anymore so the broadcaster must create another job B. The slashed transcoder re-registers after being slashed and is once again eligible to call `claimWork()` for job A because the job is still active. Now, the transcoder can choose to transcode honestly. However, the broadcaster ends up paying for 2 separate jobs when it only wants to be paying for one and the broadcaster has no way to cancel job A because a job only becomes inactive when the current block >= the job's end block.

Possible solutions:

1. When a transcoder is slashed, set the end block of the job as the current block. As a result, the job becomes inactive as soon as a the transcoder is slashed

2. Make an implementation change that allows a new transcoder to be elected if the old transcoder is slashed.

2 feels like the longer term goal, but 1 feels like the most straightforward, secure path in this moment

**Comment by ericxtang** [comment]
Ahh right... I agree option 1 feels the most straightforward for now.  I remember we used to have `EndJob` that protects against this - I forgot why we removed it.

**Comment by yondonfu** [comment]
`endJob` was removed because it introduced too many additional ways for a broadcaster to attack a transcoder i.e. ending a job before a transcoder can transfer fees to escrow with a call to `claimWork()`

So, setting a job as inactive when a transcoder is slashed by setting the job's end block to the current block is also a little tricky because a broadcaster's withdraw block (the block at which the broadcaster can withdraw its deposit) is defined as the greatest end block of any of the jobs the broadcaster has created - the idea being that a broadcaster cannot withdraw its deposit if it has any active jobs open. If we set the job's end block to the current block we do not have a good way to also modify the broadcaster's withdraw block (we don't know what the broadcaster's withdraw block should be - if the job in question's end block == broadcaster's current withdraw block we don't know what the next largest job end block is). However, maybe its ok to not modify the broadcaster's withdraw block. The implication is that when a transcoder is slashed, the job becomes inactive, and if the job's original end block is N where N is also the broadcaster's withdraw block, it is set to M s.t. M <= N where M is the current block and the broadcaster cannot withdraw its deposit until N.

**Comment by dob** [comment]
My first instinct is that I wouldn't worry too much about the transcoder becoming active again, and then continuing to do work on that same job and double charging the broadcaster.

The reason is because this is a live video stream, and the broadcaster wouldn't continue to serve segments on the original job's streamID. If they create a new job, they'd create a new streamID. there's also the defense of additional client side broadcaster logic that can handle this case and cease serving content to a transcoder who isn't assigned.

I might be missing some of the details, but gut reaction is to ignore this issue.

**Comment by yondonfu** [comment]
The transcoder might not receive any new segments, but it could still have the old signed segments that it had received previously before it was slashed. If the transcoder keeps the signed segments around it can still use them to submit additional transcode claims after it re-registers

**Comment by dob** [comment]
Hmm. What about a `mapping[transcoderAddress][jobId] => bool` that returns `true` if a transcoder has been slashed for a particular job. And then `claimWork()` would require that this mapping returns false to proceed with and allow any claim?

It's a little additional state that would have to be updated in the slash functions, but otherwise wouldn't really have to be referenced.

**Comment by yondonfu** [comment]
That would work, but is there any reason to not just set the job as inactive if no one will be able to claim work for it after the original transcoder is slashed anyway? I know there is an argument for keeping it active because ideally another transcoder will be able to take the slashed transcoder's place, but that's in the future and whether or not we set jobs as inactive in the interim likely won't affect how that change is made in the future.

**Comment by dob** [comment]
I can't think of a reason not to except for the potential "trickiness" you mentioned a couple comments up. If you don't believe that's an issue, then setting it as inactive is also fine.
