### ISSUE TITLE
Clarifications around reward cut and fee share dynamics

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#179]
Currently, reward cut is defined as the % of inflationary rewards that a transcoder will *keep* so if reward cut = X%, delegators get (100 - X)%. Meanwhile, fee share is defined as the % of fees that a transcoder will *give* so if fee share = X%, delegators get X%. I think the difference in how these two percentages work can potentially be confusing and perhaps both should work the same way i.e. reward cut is defined as the % of inflationary rewards that a transcoder will *give* so if reward cut = X%, delegators get X% and the same would apply for the fee share.

**Comment by dob** [comment]
Yes, this is of course arbitrary and debatable as to whether they should both work in the same direction. The original thinking behind the way that they were phrased is as follows:

* They would both have a tendency to be close to zero in the traditional scenario.
* All rewards should be distributed proportionally to stake - IE a block rewards cut of zero.
* All fees would be kept by transcoder for covering the cost + margin of doing the work: Fee share of zero.
* Any deviations from might be easier to mentally wrap one's head around than having one that deviates from 0 and one that deviates from 100.

But yah, of course its debatable and in the end the economics are exactly the same regardless of how it's phrased.

**Comment by yondonfu** [comment]
The reward cut and fee share dynamics remain the same - better communication at the application layer can always help with any confusion that arises so I am going to close this for now.
