### ISSUE TITLE
JobExists() vs. _jobId < numJobs

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#181]
Small thing - is there a reason we use _jobId < numJobs instead of jobExists() here?  

https://github.com/livepeer/protocol/blob/936bb90db0476e5e826cd861defb5e6972ca733f/contracts/jobs/JobsManager.sol#L351

**Comment by yondonfu** [comment]
Hm nope - should be changed to use the `jobExists()` modifier
