### ISSUE TITLE
Transcoders can leave money on the table if they submit a transcode claim right before a job's end block

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#182]
We require the job to be active in verify(). If the transcoder calls claimWork() in the last block before job.endBlock, there is a chance one of the segments should be verified, and the transcoder will not have an opportunity to do so because the job will have ended after you call claimWork().  This means you’d always have to “leave some money on the table” during the last few rounds of a job to protect yourself as a transcoder.

Yondon: Ah...yeah good point. Perhaps we remove the requirement for a job to be active for verify() so if a transcoder calls claimWork() right before the job’s end block, it can still verify any challenged segments for that last transcode claim. The additional implication is that a transcoder can call verify() for an inactive job, but I don’t think that is meaningful because the claimWork() is the function call that can actually move funds.

**Comment by dob** [comment]
Good to track this, but if we get backlogged it's not crazy to move this outside of the internal audit milestone, and address it for a future release.
