### ISSUE TITLE
Proposal - On chain availability + Round lock price matching solution to availability/job assignment problem

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#188]
## The problems

1. Currently transcoders have no way to indicate they're unavailable. This creates bad broadcaster experience.
2. Even if we had a way to indicate they were proactively unavailable, what is their incentive to call this?
3. The transcoder with the lowest price in a round, essentially has right of first refusal on all jobs. Even if other transcoders are priced only 1 wei higher, they may not get a single job. This creates a "game" in pricing to try to end up as the lowest priced transcoder. And it leads to centralization of all jobs processed by 1 or a few nodes.

## A proposed solution

1. On chain availability counter-based tracking. Set a network parameter `MaxConcurrency` with a value such as `4`. When a transcoder gets assigned a job, this parameter reduces. *(Challenge or potential blocker, we don't know when they are assigned a job on chain.)* When it hits zero, they are unavailable until they indicate availability.
   1. They also have the ability to proactively mark as unavailable at any time
   1. This solves for letting the transcoder go offline, and if they happen to go offline they'll eventually be made inactive.
    1. It also ensures that if they reach the `MaxConcurrency` then the network can react, adjust price upward, and pass work to the next available transcoder.
    1. If you want your work definitely accepted by a transcoder during a time of high usage of the network, set your price higher so that the pool of potentially available transcoders is bigger. If you only enable 1, then your transaction may fail if someone beats you in the race to claim that transcoder's final concurrency spot.
2. Downward price adjustment during Round Lock Period allowed. During this period the lowest price transcoder's price is locked. Transcoders can adjust their price down, with a limit of matching the lowest price transcoders.
   1. This allows the pool of people willing to do the work at the lowest network price to grow, encouraging decentralization and throughput at that price.
   1. If the price is too low for people to match, that's fine...maybe they'll converge around the second lowest price. And this will become the price when `MaxConcurrency` is exceeded or if the low price transcoder is inactive or goes offline.
   1. *Note, one weakness here is that it might be hard to converge on the second lowest price, as this becomes another "game" in which people may try to change at the last second to gain that position.*

### Implementation

This is clearly not fully spec'ed out, but here are some ideas:

* Availability is a map or array maintained on chain indicating the counter for each active transcoder by index.
* This is updated by the `Job(), Claim(), Available(), and Unavailable()` methods
* When a new job is created, an availability bitmap is copied into the job to be used by `electActiveTranscoder()`
* `transcoder()` function is updated to support downward price setting during the lock period if this is not already the low priced transcoder.

### Questions

* What are the effects of an arbitrarily low `MaxConcurrency` in the early days? 
   * Probably that work would be more likely to get distributed around the network and fees may be a little higher on average than they could be if all work went to the cheapest.

* Would there be games played around pricing to try and sneak into certain positions?
   * I guess for the alpha I'm less worried about this in the early days and more interested in the social + long term alignment of transcoders. I think them aligning towards the cheapest price is actually a very good outcome. And if an attacker spends stake to set an arbitrarily low price, well the rest will align around the second lowest and our client defaults will set the price a little higher such that it's likely the job gets assigned to someone available anyway.

* The blocker around not determining who a job was assigned to in the `Job()` transaction is a concern. If we wait until the `claim()` function to decrement their availability counter, then this doesn't help defend against the case where they are actually offline.

**Comment by dob** [comment]
After some discussions I'd update the proposal to:

1. Ignore availability for now. We can suggest that transcoders maintain 100% availability or else resign for the current round.

2. Implement the lock period price matching option. This would allow the network to converge a lot of transcoders to the minimum possible price, without that price converging all the way to 0...which is the only realistic convergence point with such granular pricing options if you don't lock the lowest price in as the floor.

As for implementation of this, we likely think it's only a change to the `transcoder()` function, which could have a special branch with this logic in the case that we are currently in the round lock period.

On the client, we talked about setting the default price/segment to the maximum price/segment in the active transcoder pool to give them the highest chance of being assigned to a transcoder with capacity...but of course an optimizing broadcaster could override this price to the minimum. This may or may not be a good strategy depending on how much transcode power converged to the minimum price. If very little converged there, they'd likely end up with a transcoder over capacity who couldn't handle their job.

Also on the client, we should consider a flag for transcoders that automatically matches the lowest price/round during the lock period if it's above a certain threshold that they pass in with the flag. (ie - match the lowest price if it's above 10,000 wei/segment, else leave my setting).

**Comment by dob** [comment]
One implementation challenge that came to mind: When we lock in the lowest offered price during the lock period, do we look at only the current active set rates, or all rates in the candidate set?

I see a potential attack where someone in the candidate set, who doesn't have nearly enough stake to actually be active, sets a very low rate. I can think of a number of defenses against this through various implementations and bookkeeping, but wanted to point it out so we don't ignore it. 

We either say that we assume all candidates in both pools have enough of a threshold's worth of stake to be considered evenly, or we only lock it based upon the likely active pool at the time of the round lock period. I would lean towards the latter if possible.

**Comment by ericxtang** [comment]
I think we can only be sure it's the lowest price in the active set if we also disallow `unbond()` during the lock period right?

**Comment by dob** [comment]
Another thing I wanted to make sure we're on the same page about:

The **only** adjustment allowed during the lock period is adjusting price/segment downwards. They can not change their fee share or block reward. 

Let me know if you think otherwise. I want to avoid it becoming a game at this point...I'd rather have the games played before the lock period.

**Comment by j0sh** [comment]
I'm OK with the proposed solution of a price floor during the lock period, if it means the least changes to the existing protocol. Note that this doesn't actually address the issues surrounding transcoder availability, which shouldn't be deferred for too much longer. An important part of having a robust network is accommodating unexpected changes in node availability.

**Comment by yondonfu** [comment]
@j0sh Agreed. This is definitely more of an interim temporary patch than an actual solution to the transcoder availability and job assignment issues which we should shoot to come up with ASAP after  the alpha
