### ISSUE TITLE
Mine testnet ETH for Ropsten Deployment

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#189]
We'll need ETH for our Ropsten contract deployments and test broadcasting. Set up a miner to start building a base of Ropsten ETH

**Comment by dob** [comment]
I'm on this. Currently mining with this account: https://ropsten.etherscan.io/address/0xd19f592f08d9f95d49e4740e65440e54dfecf9f0#mine

**Comment by yondonfu** [comment]
Ended up using Rinkeby in favor Ropsten - I think we consider deploying and testing on Ropsten as well at a later point
