### ISSUE TITLE
Let job creator be different from signer for broadcasted segments

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#203]
Currently, the protocol assumes that the creator of a job is the same as the signer for broadcasted segments since the `broadcasterAddress` field in the on-chain `Job` struct is populated by `msg.sender` when `JobsManager.job()` is called. 

This assumption is a blocker for certain use cases where the job creator is a contract account as opposed to a user account. Currently, a contract account can pool funds from other user accounts and call `JobsManager.deposit()` to deposit funds to be used to pay for broadcasting. However, since `JobsManager.job()` assumes that the caller is also the signer for broadcasted segments, the broadcasting workflow does not work since the contract account (the caller of `JobsManager.job()`) cannot sign segments.

The above problem can be fixed if the `job()` function signature changed from:

```
job(string _streamId, string _transcodingOptions, uint256 _maxPricePerSegment, uint256 _endBlock)
```

to

```
job(string _streamId, string _transcodingOptions, address _broadcasterAddress, uint256 _maxPricePerSegment, uint256 _endBlock)
```

such that `_broadcasterAddress` is used to populate the `broadcasterAddress` field in the on-chain `Job` struct. A contract account can then fund the broadcast by depositing funds, but designate an external user account as the signer for the broadcasted segments.

**Comment by yondonfu** [comment]
After some thinking and some discussion with @dob and @ericxtang, I think it will be better to include this change in the next version of the protocol as opposed to the initial version of the protocol at network launch. 

One reason for this is that decoupling the job creator from the broadcaster just by allowing the job creator to designate a signing broadcaster address potentially opens up certain types of replay vulnerabilities. Currently, since the protocol treats the job creator and the broadcaster as the same entity, broadcaster signatures are implicitly tied to a particular job - a broadcaster signature is only considered valid if `ecrecover(h(streamId, segNo, dataHash), broadcasterSig) == job.broadcasterAddress` where `job.broadcasterAddress` is also the job creator. If we allow the job creator to instead designate the signing broadcaster address, broadcaster signatures are no longer tied to a particular job because `job.broadcasterAddress` is controlled by the job creator (instead of always being the job creator in the previous case). The implication of this is that now broadcaster signatures for one job could be valid broadcaster signatures for any job as long as subsequent jobs are created with the same `streamId`.

Consider the following example: Alice, a job creator, designates Bob as the signing broadcaster for a new job. Note: Alice and Bob could be the same entity. Bob signs and broadcasts segments 0-10 along with signatures for each segment. Eve, another job creator, then creates another job with the same `streamId` as Alice's job and also designates Bob as the signing broadcaster for a new job even though Bob does not know about Eve. Now, all of Bob's signatures are also valid for Eve's job. 

Executing an actual attack in this example is harder, more complicated and might not even make sense in many cases, but from a secure protocol design point of view, Bob's signatures should really only be valid for a single job and any types of replays should be prevented if possible. Luckily, I think this can be solved by changing the broadcaster signature format from `sign(h(streamId, segNo, dataHash))` to `sign(h(jobId, streamId, segNo, dataHash))` which will ensure that a broadcaster's signature is only valid for a single job (since the protocol currently defines the job ID to always be monotonically increasing). However, I think it is important to dig in deeper into any additional attack vectors from such a change that touches additional code outside of just the contracts that might not be immediately obvious instead of trying to rush and include this change into the initial version of the protocol.

I do think that this functionality is pretty powerful and important, so I think it is a good candidate for an improvement proposal that could be discussed about further and prioritized for the next version of the protocol!

**Comment by ads1018** [comment]
This makes sense. Thanks for the explanation. Passing `jobId` to the signature is a nice solve. 

Agreed, best not to rush and include this change with Mainnet launch fast approaching.

**Comment by yondonfu** [comment]
Closing this issue because the protocol will no longer use on-chain jobs in Streamflow. Note: There are still plans for designated signers that can sign on behalf of a contract that deposits funds for the PM protocol in PM (see: https://github.com/livepeer/protocol/issues/252).

**Comment by adamsoffer** [comment]
Awesome 👍
