### ISSUE TITLE
Updates to feeShare, blockRewardCut, and pricePerSegment in transcoder() should be pending

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#21]
We need to differentiate between pending state and active state in transcoder() settings. One way to handle this is that whatever the transcoder sets when they call this function is considered pending. When `initializeRound()` is called, `setCurrentActiveTranscoders()` can copy the pending parameters into the active parameters for the active transcoders inside the loop.

I'm not certain whether the active states should live inside the Transcoder objects themselves, or whether the active states should be copied into some separate ActiveTranscoders structure. I could go either way.

**Comment by yondonfu** [comment]
Closed by #29
