### ISSUE TITLE
Add ability to remove a registered solver from LivepeerVerifier

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#212]
The LivepeerVerifier contract maintains a list of registered solver addresses allowed to invoke the `__callback` function. There is an `addSolver` function that the owner of the Controller can invoke to registered a specific address. There should be a `removeSolver` function that the owner of the Controller can invoke to remove a currently registered address.

**Comment by dob** [comment]
Reminder to try to use the terms block-list and allow-list, or allowed and blocked. Thanks!

**Comment by yondonfu** [comment]
Closed by #222
