### ISSUE TITLE
EndJob() and transcoding claim

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#23]
The `endJob()` transaction allows the transcoder to claim which segments they transcoded for a particular stream. The params are:

* `streamID` (or maybe jobID is better)
* `startSequenceNumber`
* `endSequenceNumber` - these two params provide the range of segments they're claiming
* merkle root of the segments they are claiming.

When this segment range is claimed, it should kick off a timer window for verification to be completed. When the block is mined, it should be deterministic which segments will be challenged (if any), based on the new block hash, verification rate, and merkle root (or other appropriate sources of unpredictability). The challenged segments don't necessarily need to be stored in state, as long as they can be calculated deterministically after the fact, though if easier to store them in state then that is ok.

The verification will kick off in a call to `Verify()` to be tracked in a separate issue.

**Comment by yondonfu** [comment]
Closed by #35
