### ISSUE TITLE
EarningsPool claimShare() calculates transcoder reward share based upon relative timing of claimEarnings() call

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#230]
The current implementation of `EarningsPool claimShare()` calculates the transcoder's reward share, prior to using that to determine the delegator's reward share, based upon how much remaining stake is in the `rewardPool`, rather than the initial amount. This means that the amount of inflationary reward that any delegator receives is impacted by the order in which they invoke `claimEarnings()` for any given round, relative to when the transcoder and other delegators invoke `claimEarnings()`. 

See: https://github.com/livepeer/protocol/blob/master/contracts/bonding/libraries/EarningsPool.sol#L76

This results in slightly unequal inflationary accounting. And can even result in tokens that will end up applied to the transcoder's stake, but aren't withdrawable by any delegator. 

The intention according to spec is that inflation is exactly proportional to stake, after the reward cut accounting. The inflationary amount should not be variable dependent upon timing of `claimEarnings()` calls. In order to retain this property, it is suggested to:

1. Use two different data structures to track the transcoder reward pool and delegator reward pool.
2. Populate these pools upon the transcoder's call to `reward()` for a given round.
3. Debit the pools upon `claimEarnings()`, following the existing logic, but avoid taking the transcoder reward pool into account when accounting for delegator rewards. 

**Note**: Fee accounting, like reward accounting, needs to be updated accordingly as well. However it was the separate requirement that additional fees can come into the pool following a reward call for a round. So the fee distribution may inevitably remain slightly unequal if users have already called `claimEarnings()` prior to the fees entering the pool within a round.

**Comment by dob** [comment]
Proposed fixes in #231

**Comment by dob** [comment]
#231 Merged, tested on Rinkeby, and deployed to mainnet. Will wait until the round kicks over for final checks and confirmations before marking as closed.

**Comment by yondonfu** [comment]
Checks complete on mainnet so closing.
