### ISSUE TITLE
Penalty escrow slashing

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#250]
We need to decide what to do with slashed funds. The easiest approach is to burn the penalty escrow. An argument against burning the penalty escrow is that is wasteful if we consider the fact that it can also be used to reimburse recipients that were harmed by a double spend.

When we decide what to do with slashed funds we should keep in mind the possibility of a double spending sender pretending to be a recipient that would be reimbursed by the penalty escrow thereby allowing the sender to recover funds

- [x] Unit test for accounting LivepeerETHTicketBroker
- [x] Unit test for updating ETH balances in LivepeerETHTicketBroker

**Comment by eladmallel** [comment]
Throwing a suggestion into the hat: let's funnel slashed value into a community funds pool, that can be governed by LPT holders and directed towards the benefit of the protocol and community (e.g. funding LIPs).

**Comment by dob** [comment]
Love the idea of funding a community DAO or charity via slashed penalty escrows. Though in the meantime we won't have any governance for that, so I suggest we start with simply burning the funds.

**Comment by yondonfu** [comment]
Closed by #261
