### ISSUE TITLE
Extract contract deployment script out of Truffle migrations

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#257]
We can extract the contract deployment scripts currently located in `migrations` into a standalone script that does not use Trufffle migrations. The benefits include:

- Avoiding unnecessary full contract deployments for every unit test
- Controlling when full contract deployments are necessary i.e. in certain integration tests
- We do not use the Truffle migration architecture anyway

**Comment by eladmallel** [comment]
👍 I like this idea! I'm not a big fan of Truffle in general, and would even consider getting rid of Truffle altogether. For example, I think we would benefit a lot from having our JS tests use web3 directly, rather than Truffle's wrappers.

**Comment by yondonfu** [comment]
Resolved by switch to hardhat.
