### ISSUE TITLE
On chain EC signature verification

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#26]
We need an on chain method/library that, given binary data, can verify that the signature was provided by a given Ethereum address. This is necessary for #24. 

I believe the `ecrecover()` function is used here, but perhaps we could use a layer of abstraction in solidity. See discussion here: https://ethereum.stackexchange.com/questions/2171/how-does-one-properly-use-ecrecover-to-verify-ethereum-signatures

**Comment by yondonfu** [comment]
Looks like work on this is already in-progress for the OpenZeppelin codebase. See this PR: https://github.com/OpenZeppelin/zeppelin-solidity/pull/257

**Comment by dob** [comment]
@yondonfu I think this is done, correct?

**Comment by yondonfu** [comment]
Yep the ECRecovery library is included in the latest OpenZeppelin release: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ECRecovery.sol

This can be closed and I'll open an issue for swapping out our current copy-and-pasted ECRecovery library for the OpenZeppelin version.
