### ISSUE TITLE
Verification interface

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#27]
The plan is to eventually use Truebit for scalable verification of selected segments. However prior to Truebit's implementation, we should create a common interface that wraps various potential backends for verification. In the short term options for implementations include Oracle, 3x transcoder verification, and even the trivial "true" verifier that just stubs a result for testing. The interface should probably specify:

* The swarm hash of the verification code to run
* The swarm hash of the input data
* The function address to invoke with the output
* The interface to providing the output (is it also a Swarm hash?)

The interface is also likely `payable`, as we'd have to pay to use Truebit or an Oracle to do verification.

**Comment by yondonfu** [comment]
Closed by #44
