### ISSUE TITLE
Batch ticket redemption

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#274]
The TicketBroker should expose a function for batch ticket redemption i.e. redeem multiple tickets in a single atomic transaction instead of submitting separate transactions for each ticket. Ideally, this function would validate all the tickets, sum the face values of each ticket and finally execute a single value transfer at the end. The simpler more naive approach would be to execute a value transfer for each ticket, but these additional value transfers are unnecessary and just increase gas usage.

**Comment by yondonfu** [comment]
1. I think the function should halt execution and return when the sender's deposit and penalty escrow are both 0. So, if B's deposit is updated in between the time at which O checks B's deposit and the time at which O's batch redemption tx is executed, O can still receive whatever value B's deposit can still cover. If a double spend is detected, the function will return after redeeming the ticket that triggers slashing.

2. I think the function can continue execution and just skip invalid tickets without reverting the entire transaction. The primary scenario where I think this might be useful is if some tickets have expired since the transaction took a bit of time to confirm and some have not. WDYT?

**Comment by eladmallel** [comment]
@yondonfu so in both answers, you're saying the function should optimize for getting as many tickets redeemed as possible, rather than employing an "all or nothing" approach. I generally agree. I think it would be great for this function to clearly communicate to its user which tickets worked and which tickets failed.

Does it sound like we're on the same page?

**Comment by yondonfu** [comment]
Yep sounds like we're on the same page.

>  I think it would be great for this function to clearly communicate to its user which tickets worked and which tickets failed.

The contract can emit an event for each successful redemption and users can use these events to determine which tickets succeeded and which failed.

**Comment by eladmallel** [comment]
> The contract can emit an event for each successful redemption and users can use these events to determine which tickets succeeded and which failed.

@yondonfu IIUC you're suggesting an event for successful redemption? - I would add an event for a failed ticket as well, just so clients won't have to wonder if a missing event is the result of a failure or some ETH client issue :)

wdyt?

**Comment by yondonfu** [comment]
We could do that, but I'm not sure that it is necessary since a client can just determine which tickets failed by diffing the tickets included in the transaction with the tickets that have successful redemption events (which can be fetched by checking the logs included in the confirmed transaction).
