### ISSUE TITLE
Consider allowing a sender to have a funded deposit + reserve along with a frozen reserve

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#292]
At the moment, if a sender's reserve is frozen, the TicketBroker contract does not allow the sender to deposit any more funds or create another reserve until the sender's current reserve is thawed. It is worth considering allowing a sender to create a new reserve and keep funding its deposit while its old reserve is still frozen (perhaps the sender accidentally overspent leading to a frozen reserve and it still wishes to use the network).

**Comment by kyriediculous** [comment]
I understand the restrictions on removing funds from the reserve when it is frozen, but why exactly are we imposing restrictions on adding funds to the reserve? Could you explain me the design thoughts behind this? Thank you !

**Comment by yondonfu** [comment]
Closing because there is no notion of reserve freezing at the moment.
