### ISSUE TITLE
Remove ActiveTranscoderSet references and usage

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#299]
In the current version of the staking protocol a new storage array is created for each round that keeps track of the active transcoders in the set, by looping over the transcoderPool ( `BondingManager.setActiveTranscoders()`. This happens when `RoundsManager.initializeRound()` is called.  Due to the extensive amount of storage r/w operations this causes a gas bottleneck when initializing rounds. 

To tackle the bottleneck we aim to get rid of `bondingManager.setActiveTranscoders()` and deprecate the mapping it sets as well as any references to this state in the `BondingManager`. 

```
    // Represents the active transcoder set
    struct ActiveTranscoderSet {
        address[] transcoders;
        mapping (address => bool) isActive;
        uint256 totalStake;
    }

    // Keep track of active transcoder set for each round
    mapping (uint256 => ActiveTranscoderSet) public activeTranscoderSet;
``` 

**Tasks** 
- Remove `Bondingmanager.setActiveTranscoders()` and its invocation in `RoundsManager.initializeRound()`
- Deprecate the `ActiveTranscoderSet` struct and it's related `activeTranscoderSet` mapping as well as any references
- Adjust unit tests

**Comment by yondonfu** [comment]
Closed by #323
