### ISSUE TITLE
Make transcoderPool a fluent representation of the active transcoder set and keep track of a transcoders totalStake for a round

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#300]
After we remove the `activeTranscoderSet` notion as described in #299 we will use the `transcoderPool` doubly linked list as a fluent representation of the active transcoder set. 

This means that we'll have to update a transcoders membership of the activeSet (remove, insert or change position) when a `bond`, `unbond` or `rebond` action occurs. 

To make sure changes to the active set don't propagate in the current round we can keep track of a transcoder's active state for the next round in its `earningsPoolPerRound` by setting a boolean flag based upon insertion or eviction from the `transcoderPool`. When the stake of a transcoder changes during a round we'll keep track of that amount on the `earningsPoolPerRound` for the next round as well. To achieve this we can use the `EarningsPool.Data.activateStake()` and `EarningsPool.Data.deactivateStake()` methods. 

The downside of this approach is that whenever a delegator delegates to a transcoder so that it becomes part of the `transcoderPool`, the delegator will pay a slightly higher gas cost for the transaction because storage operations to the `transcoderPool` need to occur.  Since the delegator will benefit from the action if the transcoder remains in the active set when the new round begins by receiving rewards, this seems like on ok tradeoff to make but we might want to do a gas cost analysis after the update to make sure the cost isn't out of line. 

**Tasks** 
- Update a transcoders membership of the `transcoderPool` and active status (in earningspool) for the next round when a bonding, unbonding or rebonding action to that transcoder occurs
- Update a transcoders `totalStake` on its earningsPool for the next round when a bonding, unbonding or rebonding action to that transcoder occurs
- Adjust unit tests

**Comment by yondonfu** [comment]
> When the stake of a transcoder changes during a round we'll keep track of that amount on the earningsPoolPerRound for the next round as well. 

I think we can reduce the # of state updates by *only* updating a transcoder's stake for `earnignsPoolPerRound[nextRound]` if the transcoder is currently going to join the active set for the next round.

**Comment by yondonfu** [comment]
Closed by #323
