### ISSUE TITLE
Keep track of a transcoder's rewardcut and feeshare on its earningsPool to 'lock in' these values for a current round

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#301]
We have to make sure that a transcoder's `rewardCut` and `feeShare` values are only updated for the next round when a transcoder decides to update these values. 

This is currently done by having the notion of a 'pending' state variable for these config parameters. These values propagated to the definitive value set for a transcoder in the `transcoders` mapping whenever a transcoder gets added to the active set in `BondingManager.setActiveTranscoders`, a dependency that we are looking to remove (see #299). 

There's two (similar) approaches to this issue: 

1. Use a transcoder's `earningsPool` to set these values for the _next round_ , similar to how we track active state and total stake in #300 
2. Have a transcoder himself lock in `feeShare` and `rewardCut` when he calls `BondingManager.Reward()` for a round, setting these values on the transcoder's `earningsPool` for the _current round_

Currently the preference seems to be going towards option 2. To complete this following tasks are needed: 

- Set the `feeShare` and `rewardCut` for a transcoder on the global `transcoders` mapping when it calls `BondingManager.transcoder()` to declare himself as a transcoder.
- Set a transcoder's `feeShare` and `rewardCut` on its earningsPool for the _current round_  when it calls `BondingManager.reward()` , locking in those values for the current round. 
- Add a conditional check to `BondingManager.Transcoder()` so that a transcoder can only update its `rewardCut` and `feeShare` for the current round when it has already called `BondingManager.Reward()` if it is active
- Deprecate `Transcoder.pendingRewardCut` and `Transcoder.pendingFeeShare` and remove its usages
- Adjust unit tests

**Comment by yondonfu** [comment]
> Add a conditional check to BondingManager.Transcoder() so that a transcoder can only update its rewardCut and feeShare for the current round when it has already called BondingManager.Reward()

In `transcoder()` we should only check if the transcoder has called `reward()` in the current round if the transcoder is active in the current round. If the transcoder is not active in the current round, then it can set its commission rates freely as the values will not be used for reward/fee pool distribution unless the transcoder is active in the current round.

**Comment by kyriediculous** [comment]
True! I should have mentioned that I was talking about an active transcoder here (implied by being able to call `reward()`) , updated the original issue to reflect this more clearly.

**Comment by yondonfu** [comment]
Closed by #323
