### ISSUE TITLE
Gas cost analysis after protocol updates

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#303]
Since the staking protocol upgrades have some serious implications on the gas cost for certain methods it would be interesting to analyse following behaviour:

- Gas cost comparison of round initialisation 
- Relationship of gas cost increase for round initialisation when number of active transcoders increases
- Cost of bonding, unbonding or rebonding if such action alters the `transcoderPool` members

**Comment by yondonfu** [comment]
Reposting here from Discord:

> I think a good next step would be to run the gas report tests with the Istanbul hardfork features enabled. The EIPs that would most impact us are 1884 (https://eips.ethereum.org/EIPS/eip-1884) which reprices opcodes (SLOAD is going from 200 -> 800) and 2020 (https://gist.github.com/karalabe/adc43c07db9f03be82093cd5466562b0) which adds net gas metering for SSTORE (will need to inspect more closely to see if we benefit from this).

Looks like a beta ganache-cli release with the Istanbul hardfork features was put out last week https://github.com/trufflesuite/ganache-cli/releases/tag/v6.8.0-istanbul.0 We should be able to run the gas report tests against this version.

**Comment by yondonfu** [comment]
Closed by #350
