### ISSUE TITLE
Select transcoder according to proportional stake (and price)

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#32]
Currently, the transcoder is selected randomly amongst the transcoders that are available for under the given price. In reality we also want to factor in their stake. Let's move towards this in iteration two.

**Comment by dob** [comment]
Was thinking about this before and saw that we still have the non-stake-based selection [given here](https://github.com/livepeer/protocol/blob/master/contracts/bonding/BondingManager.sol#L386).

```
        } else {
            // Pseudorandomly select an available transcoder that charges an acceptable price per segment
            return availableTranscoders[uint256(block.blockhash(block.number.sub(1))) % numAvailableTranscoders];
        }
```

Here's a possible algorithm for doing the weighted selection, but it requires a loop. If the # of transcoders is limited then this could work: https://stackoverflow.com/questions/2570690/python-algorithm-to-randomly-select-a-key-based-on-proportionality-weight

**Comment by dob** [comment]
This was implemented in `BondingManager.electActiveTranscoder()`, and can be closed, right?

**Comment by yondonfu** [comment]
Yep this can be closed
