### ISSUE TITLE
Update transcoder activation/deactivation events

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#338]
Currently, we have a few transcoder related events (reflects `master` branch which is the current code used on mainnet):

```
event TranscoderUpdate(address indexed transcoder, uint256 pendingRewardCut, uint256 pendingFeeShare, uint256 pendingPricePerSegment, bool registered);
event TranscoderEvicted(address indexed transcoder);
event TranscoderResigned(address indexed transcoder);
```

We can update these events to:

- Reflect the latest `BondingManager` changes i.e. removal of `pricePerSegment`
- Faciliate client side event filtering

`event TranscoderUpdate(address indexed transcoder, uint256 rewardCut, uint256 feeShare)`

Emitted whenever a transcoder updates its commission rate by calling `transcoder()`. The event can be emitted even if the values for `rewardCut` and `feeShare` are not changing.

`event TranscoderActivated(address indexed transcoder, uint256 activationRound)`

Emitted when a transcoder joins the pool in the current round and is pending activation in the next round. `activationRound` should be equal to `currentRound + 1` when this event is emitted. Clients can use this event to get a list of transcoders that are pending activation.

`event TranscoderDeactivated(address indexed transcoder, uint256 deactivationRound)`

Emitted when a transcoder is removed from the pool in the current round and is pending deactivation in the next round. `deactivationRound` should be equal to `currentRound + 1`. This event will be emitted in the following circumstances:

- The pool is full, another transcoder joins with more stake and `transcoder` has the least stake int he pool
- `transcoder` fully unbonds
- `transcoder` is slashed (not going to happen in practice for the initial SF release, but could happen in the future)

A client can watch `TranscoderActivated` and `TranscoderDeactivated` events to maintain an up-to-date view of the active set in the current round.

We should move the existing event signatures into the commented out portion of `IBondingManager.sol` in order to keep track of deprecated event signatures (clients might still want to generate topic hashes for these events).

**Comment by kyriediculous** [comment]
closed by #343
