### ISSUE TITLE
Replace deprecated throw with require(), assert()

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#37]
`throw;` is now deprecated in the latest versions of solidity, and should instead be replaced by `require()` for checks on externally provided input data, and `assert()` for checks on internal conditions that should never achieve a certain state. See: 

https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions

Also related to #34, upgrading solidity.

**Comment by yondonfu** [comment]
Done
