### ISSUE TITLE
Auto build and push ganache Docker image

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#375]
It could be useful to have CI automatically push a Docker image that includes ganache with all contracts pre-deployed and initialized. Any developer could then pull down the Docker image without having to muck around with this repo.

**Comment by kyriediculous** [comment]
There is now a docker image available : https://github.com/livepeer/docker-livepeer/pull/22

It currently uses the `streamflow` branch but we could set it up to be built from any branch for CI.

**Comment by yondonfu** [comment]
Tracking adding the image build to CI in #377 so closing this.
