### ISSUE TITLE
TicketBroker contract does not emit 'ParameterUpdate' event for protocol parameter updates. 

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#378]
The `TicketBroker` has certain setters for protocol parameters pertaining to the `pm` protocol that can be changed by the 'controller owner'.  

In other contracts in the livepeer protocol (eg. BondingManager) these types of functions emit a `ParameterUpdate(string param)` event, for the `TicketBroker` however this is not the case

**Solution you would like to see**
Emit a `ParameterUpdate` event from 
- `setUnlockPeriod()`
- `setTicketValidityPeriod()`

**Comment by yondonfu** [comment]
Closed by #522
