### ISSUE TITLE
Jobs Should Contain Multiple Video Profiles / Prices

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#40]
Currently each job has one price and one video profile.  

During Adaptive Bitrate Streaming, we want to transcode the original stream into many different streams.  In the current design, it's likely those streams will be assigned to different transcoders, which is not an efficient way for transcoding.  (For example, you can gain efficiency by transcoding the same segment into a variety of different bitrates.)

We should make the change in the protocol to allow for multiple video profiles in the same job.

Note, this introduces a change in the verification process, where `verify()` should also take in the video profile.

**Comment by dob** [comment]
I think this is supported now, correct?

**Comment by yondonfu** [comment]
Yep `job.transcodingOptions` can now contain multiple video profiles
