### ISSUE TITLE
modify test suite to work with London upgrade

### ISSUE THREAD

**Issue by kautukkundan** [livepeer/protocol#447]
solidity-coverage now uses [hardhat v2.6.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.6.0) by default which uses the London hardfork and enables eip-1559. This is causing the original tests to fail. The current workaround is to explicitly set the hardfork version to `berlin` to fall back to the old behaviour. However this needs to be corrected such that the test suite can work properly with the latest release.

- [ ] update hardhat version to v2.6.0 for local test environment
- [ ] remove hardfork = `berlin` in the config
- [ ] modify tests to pass in accordance with the new config

**Comment by yondonfu** [comment]
Closed by #457
