### ISSUE TITLE
Think about the incentives of calling EndJob

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#46]
The incentives for calling EndJob() are currently unclear. Who would call it, the transcoder or the broadcaster and would they be incentivized to call it such that the benefits outweigh the costs of an on-chain transaction?

**Comment by dob** [comment]
How about when the broadcaster requests the job they specify how many blocks they expect transcoded commitment for (default 2 hrs or something), and they pay for longer commitments? Would this make endjob unnecessary on chain and it could move to just being an off chain convenience? Everyone would know the job ended after the expiration block.

________________________________

**Comment by yondonfu** [comment]
Additional thoughts:

Currently `endJob` sets an end block such that a transcoder can still claim work and verify challenged segments in the time period before the job's end block. This is to prevent a broadcaster from receiving transcoded segments from the transcoder and calling `endJob` before a transcoder can claim work and verify challenged segments in an effort to avoid paying the fees associated with a transcoded stream.

As a type of griefing attack, a transcoder transcode all the segments, but withhold the segments from the broadcaster. The broadcaster has no way to prove the transcoder is withholding segments, so the only course of action available is to call `endJob`. However, since `endJob` only sets an end block for the job, a transcoder is still able to claim work and verify challenged segments during the time period until the end block, thereby allowing the transcoder to take fees from the broadcaster's deposit even though the transcoder is withholding segments from the broadcaster. A job's ending period could be adjusted such that a transcoder does not have enough time to go through a full claim work / verify flow once `endJob` is called, but then this would again allow a broadcaster to call `endJob` to prevent a transcoder from being able to get the fees it is owed when the transcoder has already sent all the segments to the broadcaster.

**Comment by yondonfu** [comment]
`endJob` is currently removed since jobs are assigned an end block upon creation so this can be closed
