### ISSUE TITLE
Make necessary naming changes in Confluence StakingManager

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#470]

**Comment by kyriediculous** [comment]
I think it would be good as @adamsoffer mentioned to separate the concerns for delegation and staking. 

In general it would also be good to rename all occurrences of `transcoder` to `orchestrator`

I would suggest these changes to the external API for staking


| Data structure |  Type | Description |
| -------- | -------- | -------- |
| `Orchestrator` | `struct` | Keeps track of an orchestrator's state|
| `Delegation` | `struct` | Keeps track of parameters for a delegation |
| `UnstakeLock` | `struct` | Keeps track of ongoing unstakes and undelegations |
| `unstakeLocks` | `mapping(uint256=>UnstakeLock)` | Mapping keeping track of ongoing unstakes and undelegations |
| `lastUnstakeLockID` | `uint256` | Counter keeping track of the last `UnstakeLock` stored  in `unstakeLocks` |
| `orchestratorPool` | `struct` | Doubly sorted linked list keeping track of orchestrators sorted by stake |
| `unstakePeriod` | `uint256` | Number of rounds it takes to process unstaking or undelegating |

| Function | Description |
| -------- | -------- | 
| `stake(uint256 _amount, ...hints) `     | Stake on behalf of `msg.sender`    |
| `stakeFor(uint256 _amount, address _orchestrator, ...hints)` | Stake on behalf of another orchestrator, this does not equal a delegation and should only be called if `_orchestrator` is a trusted address. |
| `getStake(address _orchestrator) returns (uint256)` | Returns the total stake for an orchestrator |
| `getOrchestrator(address _orchestrator) returns `Orchestrator`| Returns activation and reward parameters for an `Orchestrator` | 
| `delegate(uint256 _amount, address _orchestrator, ...hints)` | Delegate `_amount` of LPT to an `_orchestrator` from `msg.sender` |
| `delegateFor(uint256 _amount, address _orchestrator, address _delegator)` | `Delegate `_amount` of LPT to an `_orchestrator` on behalf of `_delegator` (Should only be called for a trusted address the ownership of the delegated LPT is assigned to `_delegator`) | 
| `getDelegation(address _delegator, address _orchestrator) returns (Delegation)` | Returns a `Delegation` for a `_delegator` to an `_orchestrator` |

**Comment by yondonfu** [comment]
Closed by #477
