### ISSUE TITLE
Separate concerns between orchestrators and delegators

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#471]
We want to separate the concerns between orchestrators and delegators. 

An orchestrator is a user that self-delegates.
The stake for this orchestrator is still allocated to the `DelegationPool` but there is an additional constraint that this delegation is flagged as special (`delegator === orchestrator`) and can not be moved to another orchestrator but only unstaked by going through the unstaking period.

**Additional Context**
- https://github.com/livepeer/protocol/issues/460
- https://github.com/livepeer/protocol/issues/470

**Comment by yondonfu** [comment]
Closed by #477
