### ISSUE TITLE
Upgrade streamflow & confluence branches to Solidity v0.8.8

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#500]
We already have a [commit](https://github.com/livepeer/protocol/commit/ae096ab6ea6d85511cce4e6357074ecaa88d74d1) that includes a bump to Solidity v0.8.4, but it also includes a bunch of other changes that don't need to be applied to these branches (i.e. a new StakingManager contract). We can extract the Solidity versioning + deps bump changes and also do a bump to v0.8.8.

Related to #499

**Comment by yondonfu** [comment]
On `streamflow`:

- Only the `BridgeMinter` needs to be on v0.8.8`

On `confluence`:

- All contracts on v0.8.8

**Comment by kautukkundan** [comment]
closed by https://github.com/livepeer/protocol/pull/537

version bumped to 0.8.9 by
https://github.com/livepeer/protocol/pull/544 
https://github.com/livepeer/protocol/pull/543
