### ISSUE TITLE
Confluence: Cleanup MathUtils vs. PreciseMathUtils library usage

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#506]
See https://github.com/livepeer/protocol/pull/496#issuecomment-998235276

**Comment by yondonfu** [comment]
I was thinking about this and at the moment I am inclined to leave the *MathUtils library usage as-is as the benefit seems to outweigh the costs.

The *MathUtils libraries are currently used in the following manner:

1. All contracts except for the Minter use MathUtils to handle percentages
2. The Minter uses MathUtilsV2 to handle percentages as of [LIP-40](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-40.md)
3. The BondingManager also uses PreciseMathUtils (in addition to MathUtils) to handle cumulative reward factor and cumulative fee factor calculations

If we switched to PreciseMathUtils for everything, we would need to:

- Update all off-chain code (go-livepeer, subgraph, explorer, etc.) to use the new level of precision for things ranging from commission rates to calculating the round lock period
- Consider the implications of reducing the max uint256 value (see https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-40.md#specification-rationale for a previous case of this) that could be used in percentage calculations in contracts when values are scaled by 10 ** 28 which is 19 more decimal places than MathUtilsV2 and 22 more decimal places than MathUtils. This might be fine, but given how many more magnitudes the max uint256 value would be when using PreciseMathUtils everywhere I'm not completely sure about the implications without putting in more thought

The main benefit I see for switching to PreciseMathUtils everywhere is consistently using a single library instead of multiple libraries with different levels of precision. At the moment, I don't think this benefit outweighs the costs outlined above given the other things we can focus on while preparing for Confluence. This doesn't preclude such a change later on, but is just based where we are at right now.

**Comment by kautukkundan** [comment]
> I don't think this benefit outweighs the costs outlined above

Yeah agreed, the implications of the change and follow up work required is too deep in scope. Let's not do this right now then. 
However, It will be nice if we revisit this in future.
