### ISSUE TITLE
Unbonding a portion of bonded stake without withdrawing as transcoder

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#51]
Transcoders (and probably delegators) should be able to unbond a portion of their bonded stake to cover costs without unbonding entirely and losing their place as a transcoder. Either we enable this, or we deposit block rewards and fees into the unbonded state. What do you think?

**Comment by ericxtang** [comment]
I think we push this off to after Snowmelt.  @dob and @yondonfu do you guys agree?

**Comment by dob** [comment]
Yes, sounds reasonable. I'd rather lock the protocol code for audit than
add another feature that isn't necessary for the security of the protocol.

**Comment by dob** [comment]
Linking to this LIP which is open for PR: https://github.com/livepeer/LIPs/pull/8

**Comment by yondonfu** [comment]
Closed by #225
