### ISSUE TITLE
Loop safety measures

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#52]
There are several spots in the protocol where we loop through a number of rounds to update state since the last time the state transitioned. For example when a delegator changes their bonding status we loop through every round since the last time they did so.

We're going to have to add limits to these loops, and allow them to invoke this function multiple times in order to get current. Otherwise we risk making these transactions impossible to finish due to gas limits.

**Comment by dob** [comment]
Two options that we considered for the case of delegators changing status and looping through each round to collect their fees:

1. Transcoders are obligated to loop through each of their delegators once per round to update their fee shares for the previous round. If they don't do this, they get slashed (and anyone else can also invoke this function and pay the fees for doing so, so the fees won't get lost). They could probably pass in an array of transcoder addresses, so they could handle hundreds or thousands per call.

One potential griefing attack is to create many attacks to delegate towards the same transcoder, causing them to pay more fees to loop through these addresses.

2. Add a safety function that lets delegators claim the fees for one round at a time. (Probably the round at which they last changed bonding status). Then it would increase the last changed bonding status by one, and then on subsequent call this would repeat, until they got to a state where they coudl loop through the change of status function.

This comes with high costs in terms of needing to execute many small transactions. But it is at least a failsafe to get the contract unstuck.

**Comment by yondonfu** [comment]
Thoughts on a possibility for eliminating the loop through claim fees for a round below. Let me know what you think..

We track a job's creation round as `job.creationRound` and the transcoder's total stake when it is assigned to the job as `job.transcoderTotalStake`. When a transcoder calls `distributeFees(jobId, claimId)`, the fees are placed in the transcoder's fee pool for `jobs[jobId].creationRound` and `jobs[_jobId].transcoderTotalStake` is assigned to the fee pool. A delegator is eligible for a fee pool if `delegator.startRound <= feePool.round`, which follows from the necessary condition `delegator.startRound <= jobs[jobId].creationRound` (this ensures that delegators do not pile onto a transcoder when they see a transcoder is assigned to a long running job that generates a lot of fees which would dilute the fee share of the delegators already bonded to the transcoder).

When a delegator triggers `autoUpdateDelegatorStake` by calling `bond` or `unbond`, it will claim from fee pools in each round from `delegator.startRound` through `currentRound`. However, if a transcoder calls `distributeFees(jobId, claimId)` after a delegator triggers `autoUpdateDelegatorStake` and `jobs[jobId].creationRound < delegator.lastStakeUpdateRound` then the delegator is not eligible for these fees. The fee tokens that the delegator is now unable to claim are held by the `Minter` contract already, so they can be considered a part of a community pool. It would be up to a delegator to carefully decided when to update its stake (either automatically via `bond` or `unbond` or manually via `updateDelegatorStake`) based on if its transcoder has an active job that it might call `distributeFees` for in the future. If a delegator knows the transcoder has fees to distribute in the next round, it might wait until the next round to perform any action to ensure that it will be able claim the fees distributed.

As for, dealing with the loop from a delegator's last stake update round through the current round, we could define the method `updateDelegatorStake(uint256 _endRound)` which allows a delegator to manually update its own stake from `delegator.lastStakeUpdateRound` through `_endRound`. A dapp might internally check how many rounds `autoUpdateDelegatorStake` would have to iterate through, divide the rounds into chunks, manually call `updateDelegatorStake` for those chunks until `autoUpdateDelegatorStake` can feasibly iterate through the rest of the rounds.

**Comment by dob** [comment]
> The fee tokens that the delegator is now unable to claim are held by the Minter contract already, so they can be considered a part of a community pool.

Would these actually be part of "a community pool" that could be accessed later, or would they be locked and irretrievable from the contract?

**Comment by dob** [comment]
One weakness of the above approach is that if a delegator has already updated state beyond a certain round, and then new fees get distributed for that round, those fees will be stuck and unclaimable, and just locked in the contract. Here's a proposed solution that closes the loop. We still need to think through the incentives however to know whether it's a good idea.

1. When a delegator calls `bond` or `unbond` to `autoUpdateDelegatorStake`, the feepool can keep track of how much stake has already been applied to the fee withdrawls for that transcoder+round. It already keeps track of the total stake for that transcoder+round.

2. When a transcoder calls `distributeFees`, the feepool will be updated. However it will look to see what proportion of fees have already been distributed for that round. This proportion of the newly added fees would currently be trapped. However, rather than have it just be trapped and unclaimable, we will instead redistribute that portion as part of the next round's round rewards. 

3. The minter should be able to keep track of this via a single state variable that gets reset to 0 each time a round is initialized and the current reward/round is calculated.

We should consider whether redistributing these "otherwise locked" tokens to everyone effects the incentives at all. Transcoders should aim to distribute the majority of the fees in a timely manner and minimize this redistribution proportion. It could be visible in their stats. 

Other options for these locked fees would be burning, or putting into a discretionary community pool

**Comment by yondonfu** [comment]
Implemented an interim solution in #86
