### ISSUE TITLE
Transcoders might want to control how much can be delegated to them

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#54]
@ericxtang brought up this idea and we discussed it briefly. Thought I'd document some of the thoughts here.

A transcoder might want to control how much can be delegated to them. One reason might be as a defense against a reputation attack from a whale. Consider this extreme case: suppose a transcoder just registered on-chain and has a hardware setup that is sufficient for a light transcoding workload. A whale can delegate a large amount to the transcoder, drastically increasing the new transcoder's total stake, pushing the transcoder into the active transcoder set in the next round. The transcoder's total stake might now be so large that it receives a much larger proportion of transcoding jobs than it was originally expecting. The transcoder's hardware setup is not powerful enough to support the number of jobs the transcoder is being elected for. As a result, the transcoder is unable to properly fulfill these jobs and takes a reputation hit. All this happens, with basically zero cost for the whale that delegates to the transcoder. The whale might even economically benefit from the attack because the transcoder will call reward and distribute a reward share to the whale if the transcoder's blockRewardCut < 100. The transcoder could set its blockRewardCut to 100, but that would not come into effect until after another round has passed.

**Comment by eladmallel** [comment]
@yondonfu @ericxtang I love this idea, and would love to revisit it as part of "Scaled Streamflow"!
