### ISSUE TITLE
Moving tokens internally across contracts

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#56]
Currently, `JobsManager` transfers tokens to `BondingManager` when a transcoder calls `distributeFees`. It is a little weird that users "deposit" tokens in both `JobsManager` and `BondingManager`. Perhaps it makes more sense to keep token management in a single contract whether it be `BondingManager` or some other treasury contract to reduce inter-contract communication and reduce the number of contracts that a user needs to approve for token transfers

**Comment by dob** [comment]
Does the addition on the Minter introduced in #75 close this issue?

**Comment by yondonfu** [comment]
Yep, this should be able to be closed once that PR is merged

**Comment by yondonfu** [comment]
Done
