### ISSUE TITLE
Add slither to github actions

### ISSUE THREAD

**Issue by RiccardoBiosas** [livepeer/protocol#567]
Slither provided some useful plugin to perform static analysis - in particular the upgradeability plugin might be a useful testing tool.
However, since static analysis is known to be quite noisy/give a fair amount of false positives, we should decide whether we should just run slither in the testing pipeline for 'awareness' or flag the github action as failed under some circumstances (i.e.: if slither detects X possibly critical issues).

**Comment by yondonfu** [comment]
> in particular the upgradeability plugin might be a useful testing tool.

Related: https://github.com/livepeer/protocol/issues/234

**Comment by yondonfu** [comment]
Will create a separate issue to track re-enable CodeQL
