### ISSUE TITLE
Transcoder's share of block reward and fees without factoring in its bonded stake

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#67]
Note: these thoughts exclusively refer to block reward, but I think they apply to both block reward and fees

Currently, a transcoder's block reward share is:
`(mintedTokens * blockRewardCut) + (delegatorsRewardShare * transcoderBond) / transcoderTotalStake)` where `delegatorsRewardShare = mintedTokens * (100 - blockRewardCut)`. A delegator's block reward share is `(delegatorsRewardShare * delegatorBond) / transcoderTotalStake`.

This slightly complicates transcoder block reward share calculation since we also have to calculate the transcoder's share of the block reward as a delegator (i.e. `(delegatorsRewardShare * transcoderBond) / transcoderTotalStake`). It also seems like there is a good chance that a transcoder's bonded stake will increase at a faster rate than a delegator's bonded stake meaning over time the delegator's block reward share will fall unless a) the delegator bonds additional tokens or b) the transcoder decreases the blockRewardCut. If the delegator's block reward share is continually falling, the delegator will just move to a different transcoder. Option A requires the delegator to purchase more tokens, so option B seems more likely. Over time, in order to provide adequate block reward share to delegators, a transcoder could end up decreasing the blockRewardCut to 0 and exclusively get block reward based on it delegated to itself.

An alternative approach that might reduce complexity is for a transcoder's block reward share to just be: `mintedTokens * blockRewardCut`. Rather than, also earning block reward based on its own bonded stake (i.e. `(delegatorsRewardShare * transcoderBond) / transcoderTotalStake`), a transcoder would set blockRewardCut to a percentage that factors in whatever amount of stake it itself has bonded. A delegator's block reward share would become `(delegatorsRewardShare * delegatorBond) / transcoderTotalDelegatedStake` such that the transcoder's bonded stake is not included in `transcoderTotalDelegatedStake`.

**Comment by dob** [comment]
After discussing this in person we're going to explore the route of treating "transcoding operations" completely independently of "delegation operations". 

Anyone can delegate towards anyone. Transcoders can activiate themselves independently of bonding (though they may be required to have some stake bonded towards them to activate). Rewards are distributed to all delegators (regardless of whether they are also a transcoder). And transcoder reward cuts are calculated independently of delegator rewards.

**Comment by yondonfu** [comment]
Closed by #70
