### ISSUE TITLE
Register all contracts in protocol registry

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#72]
Currently we are only registering the manager contracts (JobsManager, BondingManager, RoundsManager) in the protocol registry. The LivepeerToken and Verifier contracts should also be registered. The benefits of doing so:

- The node would only need to know the protocol contract address - it can use the registry to discover the addresses of all other contracts including the token contract
- The type of Verifier contract can be easily swapped out since the JobsManager would just ask the protocol registry for the address of the current Verifier contract

**Comment by ericxtang** [comment]
Is this still relevant if we use the proxy contract and controller?

**Comment by yondonfu** [comment]
Done. We register a proxy contract as "<NAME>" and the target implementation contract as "<NAME>Target". Ex. Register proxy contract as "BondingManager" and the target implementation contract as "BondingManagerTarget".
