### ISSUE TITLE
Should bond(), unbond(), transcoder()... be defined in IBondingManager?

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#74]
I was updating the Whitepaper with the Livepeer transactions, and I saw that these popular transactions aren't in the IBondingManager interface? Should the interface be updated to include them, or is it only meant to include the external functions that are called by Jobs and Rounds manager?

**Comment by yondonfu** [comment]
We don't need them right now since they are not called by any of the other contracts

**Comment by dob** [comment]
Got it. I think it's probably better practice to include all the publicly
available methods (that must be implemented) in the interface. It will make
the code more clear, as well as alternate implementations for testing or
experimentation more clear. Let's leave this issue open as a reminder so we
can get back to cleaning this up.
