### ISSUE TITLE
Fees calculated based on current round feeShare, and not job initiation round feeShare

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#85]
In the `BondingManager` `updateTranscoderWithFees()` function, the fee portion for the transcoder and delegators are calculated based upon the current round. However the job may have been initiated in a different round. This opens up the attack where a transcoder could start a bunch of jobs in a round with a high fee share, and then lower their fee share before a subsequent round when they call distribute fees.

A potential solution is the store the feeShare on the job itself, so that when the fees are distributed for that job they would be locked in.

**Comment by yondonfu** [comment]
Closed by #86
