### ISSUE TITLE
Add multisig contract for governance 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#92]

**Comment by dob** [comment]
Functionality that is considered for ownership actions:

1. Call Pause on the protocol
2. Upgrade target contract addresses for the managers/logic
3. Update protocol parameters

Over time this of course should move to decentralized governance.

**Comment by yondonfu** [comment]
This is captured by an audited external multisig that can be found here https://github.com/yondonfu/MultiSigWallet
