### ISSUE TITLE
Deploy protocol after IPFS issue is addressed

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#93]
https://github.com/livepeer/go-livepeer/issues/159

**Comment by dob** [comment]
@ericxtang is this closed now? Last issue in the Testnet Livepeer Verifier Milestone

**Comment by ericxtang** [comment]
It's deployed but we have some issues with the bonding operation.  Will close this when the bug is fixed.

**Comment by dob** [comment]
Closing this, as the network is deployed.
