### ISSUE TITLE
Delegation Game Period

### ISSUE THREAD

**Issue by ericxtang** [livepeer/protocol#95]
Adding a period between the genesis and first round, so stakes can be delegated to the full transcoder set.

**Comment by dob** [comment]
One idea here is to start the inflation rate at 0 and not allow jobs during the delegation game period. This way the protocol will be active and people can bond/delegate and the transcoder set will be calculated. Then as soon as this period ends the inflation rate gets set in initializeRound and jobs transactions now longer throw.

**Comment by yondonfu** [comment]
We did not start the network with a formal delegation period meant only for delegation. We started the network such that delegation could occur along with other protocol actions simultaneously.
