### ISSUE TITLE
GenesisManager Contract

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#97]
1. GenesisManager is deployed, and it is set as the owner of the token contract, and the “starter” of the protocol.
2. Token distribution contract is deployed
3. GenesisManager start() mints all tokens being sold to the token distribution contract
4. Users can verify before participating in the distribution that the distribution contract has a balance of 7M tokens or so. There’s no way to reduce this balance.
5. Distribution begins and ends
6. GenesisManager end() is invoked
6.1 It checks to make sure that the distribution contract is over
6.2 It reads total contributions from the distribution contract.
6.3 It calculates all allocations and assigns them based upon our own special purpose logic to handle our circumstances.
7. It transfers ownership of the token contract to the minter in the protocol.
8. It starts the protocol into the delegation period referenced in #95 
9. Users can withdraw their token from the distribution contract
9.1 After the refund period begins users can withdraw their refund from the distribution contract
(Both token withdrawls, refund withdrawls can be invoked by anyone on behalf of a user, so Livepeer could just do it).

At this point I think the distribution contract has passed its end state and all contributions + tokens have been refunded and distributed. The Genesis Manager should become useless and powerless after it transfers it’s ownership to the minter and starts the protocol. And the protocol should be live and running without any further intervention necessary.

**Comment by yondonfu** [comment]
Closed by #144
