### ISSUE TITLE
Parameter update mechanism for inflation rate

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#98]
When the protocol goes live, we'll have to parameterize it with certain values for inflation, verification rate, etc. We need a mechanism for these parameters to move in the future. Ideally we work towards decentralized governance or automatically adjusting values, but in the early days they may be moveable by more centralized mechanisms like a multisig or contract upgrade.

**Comment by dob** [comment]
Related to automatically adjusting inflation, I wrote a simulation that used the following logic:

1. Set the target bonded participation (in my case 50%).
2. At each round, calculate the % that we're off target. So if 40% is bonded, we're 10% off.
3. Move the inflation rate by the sqrt of the difference. So in this example, move by sqrt(10).

As to how this effected bonding, I randomly chose to increase or decrease the bonded amount in response to the incentives by a random number that was no less than 100,000 and no greater than 2 * the bonded difference from the target. So if we are 4,000,000 bonded with a 5,000,000 target the random number may be as large as 2,000,000.

Since we're dealing with integers, we always move at least 1% in either direction each round. 

This, of course, could be predicted since the movement is forced and restricted based on the above formula, but it pretty quickly converges to a standard inflation range. In reality, I'm not sure how quickly humans would respond to the automatically moving incentives, so we should update the simulation.

I'm interested in other suggestions for the movement function besides sqrt(difference).

**Comment by dob** [comment]
Another thing to look into: If we update parameters which are set as constants in manager contracts, then the storage value may not actually update on the forwarding contract when you deploy a new version of a target contract.

**Comment by dob** [comment]
Updating `N` the number of transcoders would potentially cause issues with the data structures that store the active and transcoder candidate pools.

**Comment by yondonfu** [comment]
Regarding updating parameters which are set as constants in manager contracts:

We could hardcode constants for protocol parameters in the `initialize` function for each manager contract which is only callable by the Controller. So, whenever we deploy a new version of the target contract we could call `upgradeContract(proxyId, targetId, newTargetContract)` in the Controller which does the following:

1. Check if the proxy contract for `proxyId` exists
2. Check if the target contract id for the proxy contract is `targetId`
3. Register `newTargetContract` as `targetId`
4. Call `initialize` on the proxy contract for `proxyId` which will forward the `initialize` call to `newTargetContract`. The `initialize` call will use the logic implemented in `newTargetContract`, but will execute in the storage context of the proxy contract for `proxyId`

The upside here would be that protocol parameters that are tweaked infrequently only during new phases of the protocol can all be updated by deploying a new version of the target contract that uses different hardcoded values for the protocol parameters.

**Comment by dob** [comment]
> The upside here would be that protocol parameters that are tweaked infrequently only during new phases of the protocol can all be updated by deploying a new version of the target contract that uses different hardcoded values for the protocol parameters.

And the downside is that we have to deploy and initialize a new version of the contract in order to update a parameter, which could otherwise be updated via a setter?

I'm not exactly sure of the ramifications of doing a contract upgrade and how transparent it is to currently running clients. I wonder if we actually would want to support both this mechanism as suggested but also have setters, which may require less coordination when doing an update? Or do you think a setter is just as disruptive?

**Comment by yondonfu** [comment]
> And the downside is that we have to deploy and initialize a new version of the contract in order to update a parameter, which could otherwise be updated via a setter?

Yep - with that in mind, as discussed offline, it might be better to individually update parameters rather than requiring a full redeploy of a manager contract which increases the range of possible vulnerabilities that could be introduced by accident

Another area of exploration discussed offline is a generic `execute` function on the Controller that accepts the data payload for a particular setter function defined on a manager contract.

**Comment by yondonfu** [comment]
Closed by #125
